//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
//Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

//Forgot Password
export const FORGOTPASSWORD_REQUEST = 'FORGOTPASSWORD_REQUEST';
export const FORGOTPASSWORD_RESPONSE = 'FORGOTPASSWORD_RESPONSE';
export const FORGOTPASSWORD_FAILED = 'FORGOTPASSWORD_FAILED';

export const GETACCOUNT_REQUEST = 'GETACCOUNT_REQUEST'
export const GETACCOUNT_FAILED = 'GETACCOUNT_FAILED'
export const GETACCOUNT_RESPONSE = 'GETACCOUNT_RESPONSE'

//UserProfile
export const LOADUSERPROFILE_REQUEST = 'LOADUSERPROFILE_REQUEST';
export const USERPROFILELOADED_RESPONSE = 'USERPROFILELOADED_RESPONSE';
export const FAILEDLOADINGUSERPROFILE_RESPONSE = 'FAILEDLOADINGUSERPROFILE_RESPONSE';

//AccountVerification
export const ACCOUNTVERIFICATION_REQUEST = 'ACCOUNTVERIFICATION_REQUEST';
export const ACCOUNTVERIFICATION_RESPONSE = 'ACCOUNTVERIFICATION_RESPONSE';
export const ACCOUNTVERIFICATION_FAILED = 'ACCOUNTVERIFICATION_FAILED';

//Myapppointments
export const MYAPPOINTMENTS_REQUEST = 'MYAPPOINTMENTS_REQUEST';
export const MYAPPOINTMENTS_RESPONSE = 'MYAPPOINTMENTS_RESPONSE';
export const MYAPPOINTMENTS_FAILED = 'MYAPPOINTMENTS_FAILED';


//Apppointment Details
export const APPOINTMENTDETAIL_REQUEST = 'APPOINTMENTDETAIL_REQUEST';
export const APPOINTMENTDETAIL_RESPONSE = 'APPOINTMENTDETAIL_RESPONSE';
export const APPOINTMENTDETAIL_FAILED = 'APPOINTMENTDETAIL_FAILED';

//Apppointment UPDATE
export const APPOINTMENTUPDATE_REQUEST = 'APPOINTMENTUPDATE_REQUEST';
export const APPOINTMENTUPDATE_RESPONSE = 'APPOINTMENTUPDATE_RESPONSE';
export const APPOINTMENTUPDATE_FAILED = 'APPOINTMENTUPDATE_FAILED';

//Apppointment ADD
export const APPOINTMENTADD_REQUEST = 'APPOINTMENTADD_REQUEST';
export const APPOINTMENTADD_RESPONSE = 'APPOINTMENTADD_RESPONSE';
export const APPOINTMENTADD_FAILED = 'APPOINTMENTADD_FAILED';

//Register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const REGISTER_FAILED = 'REGISTER_FAILED';

//Register
export const HOMEPRODUCT_REQUEST = 'HOMEPRODUCT_REQUEST';
export const HOMEPRODUCT_RESPONSE = 'HOMEPRODUCT_RESPONSE';
export const HOMEPRODUCT_FAILED = 'HOMEPRODUCT_FAILED';